### ISSUE TITLE
Pressing delete when block is focused deletes the BlockCode node

### ISSUE THREAD

**Issue by cassidyjames** [endlessm/godot-block-coding#162]
### What Happened

If I select a block and hit <kbd>Del</kbd>, I'm prompted to delete the BlockCode node in the scene tab, instead.

This was raised in the [Gamesfromscratch video around 7:05](https://youtu.be/U7n7gJIkbk0?si=3CGz3uNL2sUkzsQr&t=425), and I've confirmed it on the latest version from the AssetLib.

### How to Reproduce

1. Drag a block out to the canvas
2. Change your mind! Hit <kbd>Del</kbd>
3. See the prompt to delete the BlockCode node instead of the block

### Block Coding Plugin Version

v0.6.1 from AssetLib

### Godot Version

v4.2.2.stable.flathub [15073afe3]

### Operating System

Fedora Silverblue 40

**Comment by dbnicholson** [comment]
Ouch. Possibly all we need to do is [set the focus mode](https://docs.godotengine.org/en/stable/classes/class_control.html#class-control-property-focus-mode) on the block nodes so that they get the focus automatically. Or we can explicitly [grab the focus](https://docs.godotengine.org/en/stable/classes/class_control.html#class-control-method-grab-focus) for the block node that's being moved around.

**Comment by dbnicholson** [comment]
No, you actually need to add a handler for `KEY_DELETE`. I think I have something working, although I'm a little leery of the focusing in combination with e178d97bac141f1dc3cc30d6648b3c4224487ee8.

**Comment by manuq** [comment]
It would be nice if this is accompanied with visual feedback for the focused block, the one that will be deleted. For reference, MS Arcade has a yellow outline. This is me clicking through 3 different blocks in Arcade and finally hitting DEL on them:
[Grabación de pantalla desde 2024-07-29 14-24-35.webm](https://github.com/user-attachments/assets/454c97ce-c05f-421c-af09-f787e21bd6e9)

**Comment by dbnicholson** [comment]
> It would be nice if this is accompanied with visual feedback for the focused block, the one that will be deleted. For reference, MS Arcade has a yellow outline. This is me clicking through 3 different blocks in Arcade and finally hitting DEL on them: [Grabación de pantalla desde 2024-07-29 14-24-35.webm](https://github.com/user-attachments/assets/454c97ce-c05f-421c-af09-f787e21bd6e9)

I started working on that with the simple concept that the [Background stroke](https://github.com/endlessm/godot-block-coding/blob/def3586ba8c55540e8e3222c38cbf8ebcf777614/addons/block_code/ui/blocks/utilities/background/background.gd#L82) is dashed when it has focus. That's actually a little tricky since Godot can draw [a single dashed line](https://docs.godotengine.org/en/stable/classes/class_canvasitem.html#class-canvasitem-method-draw-dashed-line) but only a [solid polyline](https://docs.godotengine.org/en/stable/classes/class_canvasitem.html#class-canvasitem-method-draw-polyline). It actually would be simpler to draw a solid line.

A complication here is that `ControlBlock` does [a whole crazy thing](https://github.com/endlessm/godot-block-coding/blob/def3586ba8c55540e8e3222c38cbf8ebcf777614/addons/block_code/ui/blocks/control_block/control_block.gd#L105) to draw the block which is actually related to the [missing outlines](https://phabricator.endlessm.com/T35538) on some blocks.

**Comment by manuq** [comment]
@dbnicholson can the focus stroke color be solid yellow? Then you won't need to mess with dash drawing.

I'd consider the missing outlines as a separate issue. But yeah, this will make that issue very visible, we'll want to fix is sooner :)
